#
# Conda environment definition with dependencies
#
name: plinder
channels:
  - metalcycling
  - conda-forge
  - aivant
  - defaults
  - bioconda
dependencies:
  - python=3.10.*
  - reduce
  - aivant::openstructure=2.8.0
  - boost=1.82
  - mmseqs2
  - foldseek
  - plip
  - pip:
    - keyrings.google-artifactregistry-auth==1.1.2
